package app

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/bakanura/gjallarOS/internal/installer/config"
	"github.com/bakanura/gjallarOS/internal/installer/discovery"
	"github.com/bakanura/gjallarOS/internal/installer/geolocation"
	"github.com/bakanura/gjallarOS/internal/installer/prompt"
	"github.com/bakanura/gjallarOS/internal/installer/secureboot"
)

func TestRequireNixOS(t *testing.T) {
	path := filepath.Join(t.TempDir(), "os-release")
	os.WriteFile(path, []byte("ID=nixos\n"), 0644)
	if err := requireNixOS(path); err != nil {
		t.Fatal(err)
	}
	os.WriteFile(path, []byte("ID=other\n"), 0644)
	if err := requireNixOS(path); err == nil {
		t.Fatal("accepted non-NixOS")
	}
}

func TestJODSEnrollmentStartsOnlyAfterSuccessfulInstallation(t *testing.T) {
	original := runJODSCommand
	var calls [][]string
	runJODSCommand = func(_ context.Context, name string, args ...string) error {
		calls = append(calls, append([]string{name}, args...))
		return nil
	}
	t.Cleanup(func() { runJODSCommand = original })

	if err := activateJODSEnrollment(context.Background(), false); err != nil {
		t.Fatal(err)
	}
	if len(calls) != 0 {
		t.Fatalf("failed installation contacted JODS: %v", calls)
	}
	if err := activateJODSEnrollment(context.Background(), true); err != nil {
		t.Fatal(err)
	}
	joined := fmt.Sprint(calls)
	if !strings.Contains(joined, "jods-mdm-agent-enroll.service") || !strings.Contains(joined, "jods-mdm-agent-enroll.timer") {
		t.Fatalf("successful installation did not activate enrollment lifecycle: %v", calls)
	}
}

func TestInsecureJODSRequiresExplicitConfirmation(t *testing.T) {
	var output bytes.Buffer
	if err := confirmInsecureJODS(context.Background(), prompt.New(strings.NewReader("n\n"), &output)); err == nil {
		t.Fatal("insecure TLS accepted without explicit confirmation")
	}
	if err := confirmInsecureJODS(context.Background(), prompt.New(strings.NewReader("yes\n"), &output)); err != nil {
		t.Fatal(err)
	}
}

func TestUnmanagedPresetForcesJODSPrebootLockOff(t *testing.T) {
	u := config.User{EndpointManagedDevice: false, RecoveryEnable: true, JODSPrebootLockEnable: true}
	normalizeManagementSafety(&u)
	if u.JODSPrebootLockEnable {
		t.Fatal("unmanaged preset retained JODS preboot lock")
	}
}

func TestConfigureWeatherLocationRejectsDetectionAndPrompts(t *testing.T) {
	original := detectNetworkLocation
	detectNetworkLocation = func(context.Context) (geolocation.Location, error) {
		return geolocation.Location{City: "Wrong", Country: "Place"}, nil
	}
	t.Cleanup(func() { detectNetworkLocation = original })

	var output bytes.Buffer
	ui := prompt.New(strings.NewReader("n\nBerlin\nGermany\n"), &output)
	var user config.User
	if err := configureWeatherLocation(context.Background(), ui, &user, &output); err != nil {
		t.Fatal(err)
	}
	if user.WeatherCity != "Berlin" || user.WeatherCountry != "Germany" {
		t.Fatalf("unexpected weather location: %+v", user)
	}
}

func TestNormalizePreset(t *testing.T) {
}

func TestExistingInstallMarkers(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "generated", "state.nix")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	os.WriteFile(path, []byte("# Generated by gjallarctl; do not edit\n"), 0644)
	if !existingInstall(root) {
		t.Fatal("new marker not detected")
	}
}

func TestExistingInstallRejectsUnmarkedGeneratedState(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "generated", "state.nix")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	os.WriteFile(path, []byte("{ hostname = \"unrelated\"; }\n"), 0644)
	if existingInstall(root) {
		t.Fatal("unmarked generated/state.nix detected as an existing GjallarOS install")
	}
}

func TestExistingInstallMissingGeneratedStateIsNew(t *testing.T) {
	if existingInstall(t.TempDir()) {
		t.Fatal("missing generated/state.nix detected as an existing GjallarOS install")
	}
}

func TestCompletedSecureBootDoesNotRebootFirmware(t *testing.T) {
	if secureBootNeedsFirmwareReboot(secureboot.ContinuationNone) {
		t.Fatal("completed Secure Boot transaction requested a firmware reboot")
	}
	if !secureBootNeedsFirmwareReboot(secureboot.ContinuationEnroll) ||
		!secureBootNeedsFirmwareReboot(secureboot.ContinuationEnable) {
		t.Fatal("incomplete Secure Boot transaction did not request its firmware handoff")
	}
}

func TestValidateSelections(t *testing.T) {
	o := discovery.Options{
		Shells:   []string{"zsh"},
		Editors:  []string{"vscodium"},
		Browsers: []string{"librewolf"},
	}
	u := config.User{
		Shell:       "zsh",
		Editors:     []string{"vscodium"},
		Browsers:    []string{"librewolf"},
		DotfilesDir: "/repo",
	}
	if err := validateSelections(u, o); err != nil {
		t.Fatal(err)
	}

	u.Shell = "../../bad"
	if err := validateSelections(u, o); err == nil {
		t.Fatal("accepted invalid shell")
	}
}

func TestManagedPresetForcesBootRecoveryContract(t *testing.T) {
	u := config.User{
		EndpointManagedDevice: true,
	}
	normalizeManagementSafety(&u)

	if !u.SecureBootEnable {
		t.Fatal("managed preset did not force Secure Boot")
	}
	if !u.LUKSTPM2Enable {
		t.Fatal("managed preset did not force TPM2 LUKS")
	}
	if !u.RecoveryEnable {
		t.Fatal("managed preset did not force recovery")
	}
	if !u.JODSPrebootLockEnable {
		t.Fatal("managed preset did not force JODS preboot lock")
	}
}

func TestCollectProjectToolsDefaultsDisabled(t *testing.T) {
	var output bytes.Buffer
	u := config.User{}

	err := collectProjectTools(
		context.Background(),
		prompt.New(strings.NewReader("\n\n"), &output),
		&u,
	)
	if err != nil {
		t.Fatal(err)
	}
	if u.PlaneEnable || u.DrawioEnable {
		t.Fatalf("project tools should default disabled: %+v", u)
	}
	if u.PlaneHost != "" || u.DrawioHost != "" {
		t.Fatalf("disabled project tools unexpectedly received hosts: %+v", u)
	}
}

func TestCollectProjectToolsSupportsIndependentSelection(t *testing.T) {
	tests := []struct {
		name                      string
		input                     string
		planeEnable, drawioEnable bool
		drawioSelfHosted          bool
		planeHost, drawioHost     string
	}{
		{
			name:        "plane only",
			input:       "yes\nhttps://plane.example.test\nno\n",
			planeEnable: true,
			planeHost:   "https://plane.example.test",
		},
		{
			name:             "drawio only",
			input:            "no\nyes\nyes\nhttps://drawio.example.test\n",
			drawioEnable:     true,
			drawioSelfHosted: true,
			drawioHost:       "https://drawio.example.test",
		},
		{
			name:             "both",
			input:            "yes\nplane.internal:3000\nyes\nyes\ndrawio.internal:8080\n",
			planeEnable:      true,
			drawioEnable:     true,
			drawioSelfHosted: true,
			planeHost:        "http://plane.internal:3000",
			drawioHost:       "http://drawio.internal:8080",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var output bytes.Buffer
			u := config.User{}

			err := collectProjectTools(
				context.Background(),
				prompt.New(strings.NewReader(tt.input), &output),
				&u,
			)
			if err != nil {
				t.Fatal(err)
			}

			if u.PlaneEnable != tt.planeEnable ||
				u.DrawioEnable != tt.drawioEnable ||
				u.DrawioSelfHosted != tt.drawioSelfHosted ||
				u.PlaneHost != tt.planeHost ||
				u.DrawioHost != tt.drawioHost {
				t.Fatalf(
					"unexpected project-tool selection: plane=%t host=%q drawio=%t selfHosted=%t host=%q",
					u.PlaneEnable,
					u.PlaneHost,
					u.DrawioEnable,
					u.DrawioSelfHosted,
					u.DrawioHost,
				)
			}
		})
	}
}

func TestManagedPresetRequiresRecoveryPartitionProvisioning(t *testing.T) {
	u := config.User{
		EndpointManagedDevice:   true,
		RecoveryEnable:          false,
		RecoveryPartitionEnable: false,
		JODSPrebootLockEnable:   false,
		SecureBootEnable:        false,
		LUKSTPM2Enable:          false,
	}

	normalizeManagementSafety(&u)

	if !u.RecoveryEnable {
		t.Fatal("managed preset did not force recovery capability")
	}
	if !u.RecoveryPartitionEnable {
		t.Fatal("managed preset did not require dedicated recovery partition provisioning")
	}
	if !u.SecureBootEnable {
		t.Fatal("managed preset did not force Secure Boot")
	}
	if !u.LUKSTPM2Enable {
		t.Fatal("managed preset did not force TPM2 LUKS")
	}
	if !u.JODSPrebootLockEnable {
		t.Fatal("managed preset did not force JODS preboot lock")
	}
}

func TestInstalledSystemRecoveryProvisioningRequiresMaintenanceBoundary(t *testing.T) {
	s := state{
		existing: true,
		user: config.User{
			RecoveryEnable:          true,
			RecoveryPartitionEnable: true,
		},
	}

	if !s.existing {
		t.Fatal("test requires an installed GjallarOS system")
	}
	if !s.user.RecoveryPartitionEnable {
		t.Fatal("test requires recovery partition provisioning requested")
	}

	// Existing layouts are supported by GJAL-67, but root contraction is never
	// authorized against the running root. Mutation belongs to the /mnt-only
	// maintenance executor.
}

func TestRecoveryLifecycleAuthorityIsSeparated(t *testing.T) {
	// Normal installer state may update an existing recovery partition, but
	// creating/shrinking storage after installation belongs to the trusted
	// recovery environment rather than the installed operating system.
	cases := []struct {
		name             string
		existingSystem   bool
		existingRecovery bool
		allowNewStorage  bool
	}{
		{
			name:             "fresh install may provision storage",
			existingSystem:   false,
			existingRecovery: false,
			allowNewStorage:  true,
		},
		{
			name:             "installed system may not provision new storage",
			existingSystem:   true,
			existingRecovery: false,
			allowNewStorage:  false,
		},
		{
			name:             "installed system may maintain existing recovery",
			existingSystem:   true,
			existingRecovery: true,
			allowNewStorage:  false,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			newStorageAllowed := !tc.existingSystem

			if newStorageAllowed != tc.allowNewStorage {
				t.Fatalf(
					"new storage permission = %v, want %v",
					newStorageAllowed,
					tc.allowNewStorage,
				)
			}
		})
	}
}

func TestDisableTPMDependentSecurity(t *testing.T) {
	user := config.User{
		SecureBootPrompt:      true,
		SecureBootEnable:      true,
		LUKSTPM2Enable:        true,
		JODSPrebootLockEnable: true,
	}

	disableTPMDependentSecurity(&user)

	if user.SecureBootPrompt {
		t.Fatal("Secure Boot prompt remained enabled")
	}
	if user.SecureBootEnable {
		t.Fatal("Secure Boot remained enabled")
	}
	if user.LUKSTPM2Enable {
		t.Fatal("TPM2 LUKS unlock remained enabled")
	}
	if user.JODSPrebootLockEnable {
		t.Fatal("JODS preboot TPM policy remained enabled")
	}
}
