package app

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/bakanura/gjallarOS/internal/installer/config"
	"github.com/bakanura/gjallarOS/internal/installer/discovery"
	"github.com/bakanura/gjallarOS/internal/installer/geolocation"
	"github.com/bakanura/gjallarOS/internal/installer/prompt"
	"github.com/bakanura/gjallarOS/internal/installer/secureboot"
)

func TestRequireNixOS(t *testing.T) {
	path := filepath.Join(t.TempDir(), "os-release")
	os.WriteFile(path, []byte("ID=nixos\n"), 0644)
	if err := requireNixOS(path); err != nil {
		t.Fatal(err)
	}
	os.WriteFile(path, []byte("ID=other\n"), 0644)
	if err := requireNixOS(path); err == nil {
		t.Fatal("accepted non-NixOS")
	}
}

func TestJODSEnrollmentStartsOnlyAfterSuccessfulInstallation(t *testing.T) {
	original := runJODSCommand
	var calls [][]string
	runJODSCommand = func(_ context.Context, name string, args ...string) error {
		calls = append(calls, append([]string{name}, args...))
		return nil
	}
	t.Cleanup(func() { runJODSCommand = original })

	if err := activateJODSEnrollment(context.Background(), false); err != nil {
		t.Fatal(err)
	}
	if len(calls) != 0 {
		t.Fatalf("failed installation contacted JODS: %v", calls)
	}
	if err := activateJODSEnrollment(context.Background(), true); err != nil {
		t.Fatal(err)
	}
	joined := fmt.Sprint(calls)
	if !strings.Contains(joined, "jods-mdm-agent-enroll.service") || !strings.Contains(joined, "jods-mdm-agent-enroll.timer") {
		t.Fatalf("successful installation did not activate enrollment lifecycle: %v", calls)
	}
}

func TestInsecureJODSRequiresExplicitConfirmation(t *testing.T) {
	var output bytes.Buffer
	if err := confirmInsecureJODS(context.Background(), prompt.New(strings.NewReader("n\n"), &output)); err == nil {
		t.Fatal("insecure TLS accepted without explicit confirmation")
	}
	if err := confirmInsecureJODS(context.Background(), prompt.New(strings.NewReader("yes\n"), &output)); err != nil {
		t.Fatal(err)
	}
}

func TestUnmanagedPresetForcesJODSPrebootLockOff(t *testing.T) {
	u := config.User{EndpointManagedDevice: false, RecoveryEnable: true, JODSPrebootLockEnable: true}
	normalizeManagementSafety(&u)
	if u.JODSPrebootLockEnable {
		t.Fatal("unmanaged preset retained JODS preboot lock")
	}
}

func TestConfigureWeatherLocationRejectsDetectionAndPrompts(t *testing.T) {
	original := detectNetworkLocation
	detectNetworkLocation = func(context.Context) (geolocation.Location, error) {
		return geolocation.Location{City: "Wrong", Country: "Place"}, nil
	}
	t.Cleanup(func() { detectNetworkLocation = original })

	var output bytes.Buffer
	ui := prompt.New(strings.NewReader("n\nBerlin\nGermany\n"), &output)
	var user config.User
	if err := configureWeatherLocation(context.Background(), ui, &user, &output); err != nil {
		t.Fatal(err)
	}
	if user.WeatherCity != "Berlin" || user.WeatherCountry != "Germany" {
		t.Fatalf("unexpected weather location: %+v", user)
	}
}

func TestNormalizePreset(t *testing.T) {
	u := config.User{Username: "alice", KeyboardLayout: "de-latin1", WorkUserEnable: true}
	normalizePreset(&u, "/repo")
	if u.DotfilesDir != "/home/alice/Documents/gjallarOS" || u.WorkUsername != "alice-corp" || u.KeyboardLayout != "de" {
		t.Fatalf("%+v", u)
	}
}

func TestExistingInstallMarkers(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "settings.nix")
	os.WriteFile(path, []byte("# Generated by gjallarctl; do not edit\n"), 0644)
	if !existingInstall(root) {
		t.Fatal("new marker not detected")
	}
}

func TestExistingInstallRejectsUnmarkedSettings(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "settings.nix")
	os.WriteFile(path, []byte("{ hostname = \"unrelated\"; }\n"), 0644)
	if existingInstall(root) {
		t.Fatal("unmarked settings.nix detected as an existing GjallarOS install")
	}
}

func TestExistingInstallMissingSettingsIsNew(t *testing.T) {
	if existingInstall(t.TempDir()) {
		t.Fatal("missing settings.nix detected as an existing GjallarOS install")
	}
}

func TestCompletedSecureBootDoesNotRebootFirmware(t *testing.T) {
	if secureBootNeedsFirmwareReboot(secureboot.ContinuationNone) {
		t.Fatal("completed Secure Boot transaction requested a firmware reboot")
	}
	if !secureBootNeedsFirmwareReboot(secureboot.ContinuationEnroll) ||
		!secureBootNeedsFirmwareReboot(secureboot.ContinuationEnable) {
		t.Fatal("incomplete Secure Boot transaction did not request its firmware handoff")
	}
}

func TestValidateSelections(t *testing.T) {
	o := discovery.Options{Profiles: []string{"laptop"}, Shells: []string{"zsh"}, Editors: []string{"vscodium"}, Browsers: []string{"librewolf"}, Themes: []string{"noctalia"}}
	u := config.User{Profile: "laptop", Shell: "zsh", Editors: []string{"vscodium"}, Browsers: []string{"librewolf"}, Theme: "noctalia", DotfilesDir: "/repo"}
	if err := validateSelections(u, o); err != nil {
		t.Fatal(err)
	}
	u.Profile = "../../bad"
	if err := validateSelections(u, o); err == nil {
		t.Fatal("accepted invalid profile")
	}
}

func TestManagedPresetForcesBootRecoveryContract(t *testing.T) {
	u := config.User{
		EndpointManagedDevice: true,
	}
	normalizeManagementSafety(&u)

	if !u.SecureBootEnable {
		t.Fatal("managed preset did not force Secure Boot")
	}
	if !u.LUKSTPM2Enable {
		t.Fatal("managed preset did not force TPM2 LUKS")
	}
	if !u.RecoveryEnable {
		t.Fatal("managed preset did not force recovery")
	}
	if !u.JODSPrebootLockEnable {
		t.Fatal("managed preset did not force JODS preboot lock")
	}
}

func TestCollectProjectToolsDefaultsDisabled(t *testing.T) {
	var output bytes.Buffer
	u := config.User{}

	err := collectProjectTools(
		context.Background(),
		prompt.New(strings.NewReader("\n\n"), &output),
		&u,
	)
	if err != nil {
		t.Fatal(err)
	}
	if u.PlaneEnable || u.DrawioEnable {
		t.Fatalf("project tools should default disabled: %+v", u)
	}
	if u.PlaneHost != "" || u.DrawioHost != "" {
		t.Fatalf("disabled project tools unexpectedly received hosts: %+v", u)
	}
}

func TestCollectProjectToolsSupportsIndependentSelection(t *testing.T) {
	tests := []struct {
		name                      string
		input                     string
		planeEnable, drawioEnable bool
		planeHost, drawioHost     string
	}{
		{
			name:        "plane only",
			input:       "yes\nhttps://plane.example.test\nno\n",
			planeEnable: true,
			planeHost:   "https://plane.example.test",
		},
		{
			name:         "drawio only",
			input:        "no\nyes\nhttps://drawio.example.test\n",
			drawioEnable: true,
			drawioHost:   "https://drawio.example.test",
		},
		{
			name:         "both",
			input:        "yes\nplane.internal:3000\nyes\ndrawio.internal:8080\n",
			planeEnable:  true,
			drawioEnable: true,
			planeHost:    "plane.internal:3000",
			drawioHost:   "drawio.internal:8080",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var output bytes.Buffer
			u := config.User{}

			err := collectProjectTools(
				context.Background(),
				prompt.New(strings.NewReader(tt.input), &output),
				&u,
			)
			if err != nil {
				t.Fatal(err)
			}

			if u.PlaneEnable != tt.planeEnable ||
				u.DrawioEnable != tt.drawioEnable ||
				u.PlaneHost != tt.planeHost ||
				u.DrawioHost != tt.drawioHost {
				t.Fatalf(
					"unexpected project-tool selection: plane=%t host=%q drawio=%t host=%q",
					u.PlaneEnable,
					u.PlaneHost,
					u.DrawioEnable,
					u.DrawioHost,
				)
			}
		})
	}
}
