package app

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/bakanura/gjallarOS/internal/installer/config"
	"github.com/bakanura/gjallarOS/internal/installer/discovery"
	"github.com/bakanura/gjallarOS/internal/installer/geolocation"
	"github.com/bakanura/gjallarOS/internal/installer/prompt"
	"github.com/bakanura/gjallarOS/internal/installer/secureboot"
)

func TestRequireNixOS(t *testing.T) {
	path := filepath.Join(t.TempDir(), "os-release")
	os.WriteFile(path, []byte("ID=nixos\n"), 0644)
	if err := requireNixOS(path); err != nil {
		t.Fatal(err)
	}
	os.WriteFile(path, []byte("ID=other\n"), 0644)
	if err := requireNixOS(path); err == nil {
		t.Fatal("accepted non-NixOS")
	}
}

func TestConfigureWeatherLocationRejectsDetectionAndPrompts(t *testing.T) {
	original := detectNetworkLocation
	detectNetworkLocation = func(context.Context) (geolocation.Location, error) {
		return geolocation.Location{City: "Wrong", Country: "Place"}, nil
	}
	t.Cleanup(func() { detectNetworkLocation = original })

	var output bytes.Buffer
	ui := prompt.New(strings.NewReader("n\nBerlin\nGermany\n"), &output)
	var user config.User
	if err := configureWeatherLocation(context.Background(), ui, &user, &output); err != nil {
		t.Fatal(err)
	}
	if user.WeatherCity != "Berlin" || user.WeatherCountry != "Germany" {
		t.Fatalf("unexpected weather location: %+v", user)
	}
}

func TestNormalizePreset(t *testing.T) {
	u := config.User{Username: "alice", KeyboardLayout: "de-latin1", WorkUserEnable: true}
	normalizePreset(&u, "/repo")
	if u.DotfilesDir != "/home/alice/Documents/gjallarOS" || u.WorkUsername != "alice-corp" || u.KeyboardLayout != "de" {
		t.Fatalf("%+v", u)
	}
}

func TestExistingInstallMarkers(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "settings.nix")
	os.WriteFile(path, []byte("# Generated by gjallarctl; do not edit\n"), 0644)
	if !existingInstall(root) {
		t.Fatal("new marker not detected")
	}
}

func TestExistingInstallRejectsUnmarkedSettings(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "settings.nix")
	os.WriteFile(path, []byte("{ hostname = \"unrelated\"; }\n"), 0644)
	if existingInstall(root) {
		t.Fatal("unmarked settings.nix detected as an existing GjallarOS install")
	}
}

func TestExistingInstallMissingSettingsIsNew(t *testing.T) {
	if existingInstall(t.TempDir()) {
		t.Fatal("missing settings.nix detected as an existing GjallarOS install")
	}
}

func TestCompletedSecureBootDoesNotRebootFirmware(t *testing.T) {
	if secureBootNeedsFirmwareReboot(secureboot.ContinuationNone) {
		t.Fatal("completed Secure Boot transaction requested a firmware reboot")
	}
	if !secureBootNeedsFirmwareReboot(secureboot.ContinuationEnroll) ||
		!secureBootNeedsFirmwareReboot(secureboot.ContinuationEnable) {
		t.Fatal("incomplete Secure Boot transaction did not request its firmware handoff")
	}
}

func TestValidateSelections(t *testing.T) {
	o := discovery.Options{Profiles: []string{"laptop"}, Shells: []string{"zsh"}, Editors: []string{"vscodium"}, Browsers: []string{"librewolf"}, Themes: []string{"noctalia"}}
	u := config.User{Profile: "laptop", Shell: "zsh", Editors: []string{"vscodium"}, Browsers: []string{"librewolf"}, Theme: "noctalia", DotfilesDir: "/repo"}
	if err := validateSelections(u, o); err != nil {
		t.Fatal(err)
	}
	u.Profile = "../../bad"
	if err := validateSelections(u, o); err == nil {
		t.Fatal("accepted invalid profile")
	}
}
