#!/usr/bin/env bash
set -euo pipefail

# Repository-compatible entrypoint. The deployed command is generated by
# default.nix and points at the Nix-built gjallarctl binary directly.
REPO_ROOT="${REPO_ROOT:-$HOME/Documents/gjallarOS}"

command -v gjallarctl >/dev/null 2>&1 || {
    printf '%s\n' 'ERROR: gjallarctl is unavailable; rebuild GjallarOS first.' >&2
    exit 127
}

exec gjallarctl check --repo "$REPO_ROOT" "$@"
