render_settings() {
    local target="$1" temporary
    temporary="${target}.tmp.$$"
    {
        printf '{pkgs, inputs, ...}:\nrec {\n'
        printf '    # Generated by scripts/installation/install.sh.\n'
        printf '    system = "%s";\n' "$(nix_string "$cfg_system")"
        printf '    profile = "%s";\n' "$(nix_string "$cfg_profile")"
        printf '    hostname = "%s";\n' "$(nix_string "$cfg_hostname")"
        printf '    username = "%s";\n' "$(nix_string "$cfg_username")"
        printf '    timezone = "%s";\n' "$(nix_string "$cfg_timezone")"
        printf '    locale = "%s";\n' "$(nix_string "$cfg_locale")"
        printf '    name = "%s";\n' "$(nix_string "$cfg_name")"
        printf '    email = "%s";\n' "$(nix_string "$cfg_email")"
        printf '    githubUsername = "%s";\n' "$(nix_string "$cfg_github_username")"
        printf '    dotfilesDir = "%s";\n\n' "$(nix_string "$cfg_dotfiles_dir")"
        printf '    workUserEnable = %s;\n' "$cfg_work_user_enable"
        printf '    workUsername = "%s";\n\n' "$(nix_string "$cfg_work_username")"
        printf '    dockerEnable = %s;\n\n' "$cfg_docker_enable"
        printf '    shell = "%s";\n' "$(nix_string "$cfg_shell")"
        printf '    editors = '; nix_list "${cfg_editors[@]}"; printf ';\n'
        printf '    browsers = '; nix_list "${cfg_browsers[@]}"; printf ';\n'
        printf '    preferredEditor = "%s";\n' "$(nix_string "$cfg_preferred_editor")"
        printf '    preferredBrowser = "%s";\n\n' "$(nix_string "$cfg_preferred_browser")"
        printf '    # Optional per-user wallpaper paths (empty uses the selected theme).\n'
        printf '    backgroundNormal = "%s";\n' "$(nix_string "$cfg_background_normal")"
        printf '    backgroundWork = "%s";\n' "$(nix_string "$cfg_background_work")"
        printf '    backgroundGaming = "%s";\n\n' "$(nix_string "$cfg_background_gaming")"
        printf '    enableScrobbling = %s;\n' "$cfg_enable_scrobbling"
        printf '    enableLastfm = %s;\n' "$cfg_enable_lastfm"
        printf '    enableListenbrainz = %s;\n' "$cfg_enable_listenbrainz"
        printf '    lastfmUsername = "%s";\n' "$(nix_string "$cfg_lastfm_username")"
        printf '    listenbrainzUsername = "%s";\n\n' "$(nix_string "$cfg_listenbrainz_username")"
        printf '    frameworkEnable = %s;\n' "$cfg_framework_enable"
        printf '    frameworkModel = "%s";\n\n' "$(nix_string "$cfg_framework_model")"
        printf '    graphicsVendor = "%s";\n' "$(nix_string "$cfg_graphics_vendor")"
        printf '    graphicsType = "%s";\n' "$(nix_string "$cfg_graphics_type")"
        printf '    graphicsCompute = %s;\n' "$cfg_graphics_compute"
        printf '    graphicsBusId = "%s";\n' "$(nix_string "$cfg_graphics_bus_id")"
        printf '    graphicsIntegratedBusId = "%s";\n' "$(nix_string "$cfg_graphics_integrated_bus_id")"
        printf '    wifiDriver = "%s";\n\n' "$(nix_string "$cfg_wifi_driver")"
        printf '    aiEnable = %s;\n' "$cfg_ai_enable"
        printf '    aiModel = "%s";\n\n' "$(nix_string "$cfg_ai_model")"
        printf '    aiContextTokens = %s;\n\n' "$cfg_ai_context_tokens"
        printf '    aiVramMB = %s;\n\n' "$cfg_ai_vram_mb"
        printf '    nemuEnable = %s;\n' "$cfg_nemu_enable"
        printf '    nemuGpuPassthrough = %s;\n' "$cfg_nemu_gpu_passthrough"
        printf '    nemuGpuIds = '; nix_list "${cfg_nemu_gpu_ids[@]}"; printf ';\n\n'
        printf '    luksTpm2Enable = %s;\n\n' "$cfg_luks_tpm2_enable"
        printf '    wms = '; nix_list "${cfg_wms[@]}"; printf ';\n'
        printf '    theme = "%s";\n\n' "$(nix_string "$cfg_theme")"
        printf '    profileDetails = import (./. + "/profiles/${profile}/details.nix") {};\n'
        printf '    themeDetails = import (./. + "/themes/${theme}.nix") {inherit pkgs;};\n'
        printf '}\n'
    } > "$temporary"
    mv -- "$temporary" "$target"
    say "Wrote $target"
}
