{pkgs, inputs, ...}:
rec {
    # Generated by scripts/installation/install.sh.
    system = "x86_64-linux";
    profile = "laptop";
    hostname = "gjallarOS";
    username = "baka";
    timezone = "Europe/Berlin";
    locale = "en_US.UTF-8";
    keyboardLayout = "de";
    keyboardVariant = "";
    touchpadWorkspaceSwipe = true;
    clamshellEnable = true;
    usbguardEnable = false;
    name = "bakanura";
    email = "bakanura@proton.me";
    githubUsername = "bakanura";
    dotfilesDir = "/home/baka/Documents/gjallarOS";

    workUserEnable = true;
    workUsername = "baka-corp";
    workUserPasswordFile = "/var/lib/gjallarOS/passwords/baka-corp.hash";

    dockerEnable = true;

    debugFunctions = false;

    shell = "zsh";
    editors = [ "vscodium" ];
    browsers = [ "librewolf" ];
    preferredEditor = "vscodium";
    preferredBrowser = "librewolf";

    # Optional per-user wallpaper paths (empty uses the selected theme).
    backgroundNormal = "/home/baka/Documents/gjallarOS/non-nix/wallpapers/sword.jpg";
    backgroundWork = "/home/baka/Documents/gjallarOS/non-nix/wallpapers/nord.png";
    backgroundGaming = "";

    enableScrobbling = false;
    enableLastfm = false;
    enableListenbrainz = false;
    lastfmUsername = "";
    listenbrainzUsername = "";

    frameworkEnable = true;
    frameworkModel = "13";

    graphicsVendor = "amd";
    graphicsType = "integrated";
    graphicsCompute = true;
    graphicsBusId = "PCI:193:0:0";
    graphicsIntegratedBusId = "PCI:193:0:0";
    wifiDriver = "rtw89pci";

    aiEnable = true;
    aiModel = "qwen3-coder:30b";

    aiContextTokens = 32768;

    aiVramMB = 2048;

    nemuEnable = true;
    nemuGpuPassthrough = false;
    nemuGpuIds = [ "1002:15bf" ];

    luksTpm2Enable = false;

    wms = [ "hyprland" ];
    theme = "catppuccin";

    profileDetails = import (./. + "/profiles/${profile}/details.nix") {};
    themeDetails = import (./. + "/themes/${theme}.nix") {inherit pkgs;};
}
