{
  inputs,
  config,
  lib,
  settings,
  pkgs,
  ...
}:
let
  # The selected theme owns the shell choice; keep Hyprland itself stable.
  shell = settings.themeDetails.shell or "noctalia";
in
{
  _module.args.hyprlandShellDetails = import (../. + "/shells/${shell}/details.nix") {
    inherit
      pkgs
      inputs
      lib
      config
      ;
  };
  imports = [
    ./env.nix
    ./binds.nix
    ./scripts.nix
    ./rules.nix
    ./plugins.nix
    ./hyprlock.nix
    ../shells/${shell}
    ./settings.nix
  ];

  home.packages = with pkgs; [
    hyprcursor
    nwg-displays
  ];

  # nwg-displays owns these files.  Empty initial files keep Home Manager's
  # generated Hyprland config valid until the user saves a display layout.
  home.activation.gjallarHyprlandDisplayConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    display_config_dir="$HOME/.config/hypr"
    ${pkgs.coreutils}/bin/mkdir -p "$display_config_dir"
    for display_config in monitors.conf workspaces.conf; do
      if [ ! -e "$display_config_dir/$display_config" ]; then
        : > "$display_config_dir/$display_config"
      fi
    done
  '';

  wayland.windowManager.hyprland = {
    enable = true;
    configType = "hyprlang";
    # package = inputs.hyprland.packages.${pkgs.system}.hyprland;
    package = pkgs.hyprland;
    systemd.enable = true;
    # Noctalia owns this generated include.  It is a normal user-writable
    # state file, while this Home Manager config remains immutable.
    extraConfig = ''
      source = ~/.local/state/noctalia/hyprland-colors.conf
      # User-writable display layout generated by nwg-displays.
      source = ~/.config/hypr/monitors.conf
      source = ~/.config/hypr/workspaces.conf
    '';
    plugins = [
      # inputs.hypr-dynamic-cursors.packages.${pkgs.system}.hypr-dynamic-cursors
      # pkgs.hyprlandPlugins.hypr-dynamic-cursors
    ]
    ++
      lib.optional (settings.themeDetails.bordersPlusPlus)
        # inputs.hyprland-plugins.packages.${pkgs.system}.borders-plus-plus;
        pkgs.hyprlandPlugins.borders-plus-plus;
  };

  xdg.portal = {
    enable = true;
    xdgOpenUsePortal = true;
    config = {
      hyprland.default = [ "hyprland" ];
    };
  };
}
