// Package nixrender emits the small Nix literal subset used by installer
// generated settings. It deliberately has no evaluation capability.
package nixrender

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// String returns a Nix double-quoted string literal. In addition to ordinary
// quoting it escapes interpolation markers, so a value from user.config.json
// can never become executable Nix during settings rendering.
func String(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "\"", "\\\"")
	value = strings.ReplaceAll(value, "${", "\\${")
	value = strings.ReplaceAll(value, "\n", "\\n")
	value = strings.ReplaceAll(value, "\r", "\\r")
	return "\"" + value + "\""
}

func Strings(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, String(value))
	}
	return "[ " + strings.Join(quoted, " ") + " ]"
}

// Settings contains only values written to settings.nix. Values are rendered
// as literals; none are evaluated as Nix source.
type Settings struct {
	System, Profile, Hostname, Username, Timezone, Locale string
	KeyboardLayout, KeyboardVariant                       string
	WeatherCity, WeatherCountry                           string
	TouchpadWorkspaceSwipe, TouchscreenEnable             bool
	PenTabletEnable                                       bool
	ClamshellEnable, USBGuardEnable                       bool
	Name, Email, GitHubUsername, DotfilesDir              string
	WorkUserEnable                                        bool
	WorkUsername, WorkUserPasswordFile, RootPasswordFile  string
	DockerEnable, DebugFunctions                          bool
	Shell                                                 string
	Editors, Browsers                                     []string
	PreferredEditor, PreferredBrowser                     string
	PlaneHost, DrawioHost                                 string
	PlaneEnable, DrawioEnable, DrawioSelfHosted           bool
	BackgroundNormal, BackgroundWork, BackgroundGaming    string
	EnableScrobbling, EnableLastfm, EnableListenbrainz    bool
	LastfmUsername, ListenbrainzUsername                  string
	FrameworkEnable                                       bool
	FrameworkModel, GraphicsVendor, GraphicsType          string
	GraphicsCompute                                       bool
	GraphicsBusID, GraphicsIntegratedBusID, WiFiDriver    string
	AIEnable                                              bool
	AIModel, AIAccelerationProfile                        string
	AIAgentMode                                           string
	AIContextTokens, AIVRAMMB                             int
	NemuEnable, NemuGPUPassthrough                        bool
	NemuGPUIDs                                            []string
	LUKSTPM2Enable                                        bool
	RecoveryEnable, JODSPrebootLockEnable                 bool
	SecureBootEnable                                      bool
	EndpointManagedDevice                                 bool
	JODSEndpoint, JODSPolicySigningPublicKey              string
	JODSRecoveryCommandSigningPublicKey                   string
	JODSEnrollmentMode                                    string
	JODSAllowInsecureTLS                                  bool
	JODSDeviceClass, JODSDesktopProfile                   string
	JODSFingerprintEnrollmentAllowed                      bool
	WMs                                                   []string
	Theme                                                 string
}

func Render(s Settings) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "{pkgs, inputs, ...}:")
	fmt.Fprintln(&b, "rec {")
	fmt.Fprintln(&b, "    # Generated by gjallarctl; do not edit by hand.")
	str := func(k, v string) { fmt.Fprintf(&b, "    %s = %s;\n", k, String(v)) }
	boolean := func(k string, v bool) { fmt.Fprintf(&b, "    %s = %t;\n", k, v) }
	integer := func(k string, v int) { fmt.Fprintf(&b, "    %s = %d;\n", k, v) }
	list := func(k string, v []string) { fmt.Fprintf(&b, "    %s = %s;\n", k, Strings(v)) }
	str("system", s.System)
	str("profile", s.Profile)
	str("hostname", s.Hostname)
	str("username", s.Username)
	str("timezone", s.Timezone)
	str("locale", s.Locale)
	str("keyboardLayout", s.KeyboardLayout)
	str("keyboardVariant", s.KeyboardVariant)
	str("weatherCity", s.WeatherCity)
	str("weatherCountry", s.WeatherCountry)
	boolean("touchpadWorkspaceSwipe", s.TouchpadWorkspaceSwipe)
	boolean("touchscreenEnable", s.TouchscreenEnable)
	boolean("penTabletEnable", s.PenTabletEnable)
	boolean("clamshellEnable", s.ClamshellEnable)
	boolean("usbguardEnable", s.USBGuardEnable)
	str("name", s.Name)
	str("email", s.Email)
	str("githubUsername", s.GitHubUsername)
	str("dotfilesDir", s.DotfilesDir)
	boolean("workUserEnable", s.WorkUserEnable)
	str("workUsername", s.WorkUsername)
	str("workUserPasswordFile", s.WorkUserPasswordFile)
	str("rootPasswordFile", s.RootPasswordFile)
	boolean("dockerEnable", s.DockerEnable)
	boolean("debugFunctions", s.DebugFunctions)
	str("shell", s.Shell)
	list("editors", s.Editors)
	list("browsers", s.Browsers)
	str("preferredEditor", s.PreferredEditor)
	str("preferredBrowser", s.PreferredBrowser)
	boolean("planeEnable", s.PlaneEnable)
	str("planeHost", s.PlaneHost)
	boolean("drawioEnable", s.DrawioEnable)
	boolean("drawioSelfHosted", s.DrawioSelfHosted)
	str("drawioHost", s.DrawioHost)
	str("backgroundNormal", s.BackgroundNormal)
	str("backgroundWork", s.BackgroundWork)
	str("backgroundGaming", s.BackgroundGaming)
	boolean("enableScrobbling", s.EnableScrobbling)
	boolean("enableLastfm", s.EnableLastfm)
	boolean("enableListenbrainz", s.EnableListenbrainz)
	str("lastfmUsername", s.LastfmUsername)
	str("listenbrainzUsername", s.ListenbrainzUsername)
	boolean("frameworkEnable", s.FrameworkEnable)
	str("frameworkModel", s.FrameworkModel)
	str("graphicsVendor", s.GraphicsVendor)
	str("graphicsType", s.GraphicsType)
	boolean("graphicsCompute", s.GraphicsCompute)
	str("graphicsBusId", s.GraphicsBusID)
	str("graphicsIntegratedBusId", s.GraphicsIntegratedBusID)
	str("wifiDriver", s.WiFiDriver)
	boolean("aiEnable", s.AIEnable)
	str("aiModel", s.AIModel)
	str("aiAccelerationProfile", s.AIAccelerationProfile)
	str("aiAgentMode", s.AIAgentMode)
	integer("aiContextTokens", s.AIContextTokens)
	integer("aiVramMB", s.AIVRAMMB)
	boolean("nemuEnable", s.NemuEnable)
	boolean("nemuGpuPassthrough", s.NemuGPUPassthrough)
	list("nemuGpuIds", s.NemuGPUIDs)
	boolean("luksTpm2Enable", s.LUKSTPM2Enable)
	boolean("recoveryEnable", s.RecoveryEnable)
	boolean("jodsPrebootLockEnable", s.JODSPrebootLockEnable)
	boolean("secureBootEnable", s.SecureBootEnable)
	boolean("endpointManagedDevice", s.EndpointManagedDevice)
	str("jodsEndpoint", s.JODSEndpoint)
	str("jodsPolicySigningPublicKey", s.JODSPolicySigningPublicKey)
	str("jodsRecoveryCommandSigningPublicKey", s.JODSRecoveryCommandSigningPublicKey)
	str("jodsEnrollmentMode", s.JODSEnrollmentMode)
	boolean("jodsAllowInsecureTls", s.JODSAllowInsecureTLS)
	str("jodsDeviceClass", s.JODSDeviceClass)
	str("jodsDesktopProfile", s.JODSDesktopProfile)
	boolean("jodsFingerprintEnrollmentAllowed", s.JODSFingerprintEnrollmentAllowed)
	list("wms", s.WMs)
	str("theme", s.Theme)
	fmt.Fprintln(&b, "    profileDetails = import (./. + \"/profiles/${profile}/details.nix\") {};")
	fmt.Fprintln(&b, "    themeDetails = import (./. + \"/themes/${theme}.nix\") {inherit pkgs;};")
	fmt.Fprintln(&b, "}")
	return b.Bytes()
}

// WriteAtomic writes through a sibling temporary file then renames it.
func WriteAtomic(path string, s Settings) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".settings.nix-*")
	if err != nil {
		return fmt.Errorf("create temporary settings: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if err := tmp.Chmod(0644); err != nil {
		tmp.Close()
		return fmt.Errorf("set settings permissions: %w", err)
	}
	if _, err := tmp.Write(Render(s)); err != nil {
		tmp.Close()
		return fmt.Errorf("write settings: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return fmt.Errorf("sync settings: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close settings: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("replace settings: %w", err)
	}
	return nil
}
